### ISSUE TITLE
BCD Verifier test result

### ISSUE THREAD

**Issue by Ramon-Zarat** [flamewing/68k-bcd-verifier#4]
Working:

MAME 
Higan
Mednafen

Not working:

AGES
DGEN SDL
GENS, and all of its derivatives. (Debugens, GENS32, GENS+ GENS GS etc...)
GENSX
Genadrive
Genem
Generator32
Genesis Plus
Genital32
Megasis
Morphgear
Picodrive
Retrodrive
SegaEmu
SmartGear
Vegas
Xe
Xega

**Comment by flamewing** [comment]
Thanks!
